// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Appointermnt struct {
	ID                 int32         `json:"id"`
	UserID             sql.NullInt32 `json:"user_id"`
	TypeAvailabilityID sql.NullInt32 `json:"type_availability_id"`
	IsAccepted         sql.NullInt32 `json:"is_accepted"`
	IsRejected         sql.NullInt32 `json:"is_rejected"`
	IsPending          sql.NullInt32 `json:"is_pending"`
	Status             sql.NullInt32 `json:"status"`
	CreatedDate        sql.NullTime  `json:"created_date"`
	UpdatedDate        sql.NullTime  `json:"updated_date"`
	DeletedDate        sql.NullTime  `json:"deleted_date"`
}

type Availability struct {
	ID                int32         `json:"id"`
	ServiceID         sql.NullInt32 `json:"service_id"`
	ServiceProviderID sql.NullInt32 `json:"service_provider_id"`
	Status            sql.NullInt32 `json:"status"`
	IsActive          sql.NullInt32 `json:"is_active"`
	CreatedDate       sql.NullTime  `json:"created_date"`
	UpdatedDate       sql.NullTime  `json:"updated_date"`
	DeletedDate       sql.NullTime  `json:"deleted_date"`
}

type Service struct {
	ID          int32          `json:"id"`
	ServiceType sql.NullString `json:"service_type"`
	IsActive    sql.NullInt32  `json:"is_active"`
	Status      sql.NullInt32  `json:"status"`
	CreatedDate sql.NullTime   `json:"created_date"`
	UpdatedDate sql.NullTime   `json:"updated_date"`
	DeletedDate sql.NullTime   `json:"deleted_date"`
}

type ServiceProvider struct {
	ID                int32          `json:"id"`
	ServiceID         sql.NullInt32  `json:"service_id"`
	Username          sql.NullString `json:"username"`
	FirstName         sql.NullString `json:"first_name"`
	LastName          sql.NullString `json:"last_name"`
	PrePassword       sql.NullString `json:"pre_password"`
	Password          sql.NullString `json:"password"`
	EncryptedPasswrod sql.NullString `json:"encrypted_passwrod"`
	Address           sql.NullString `json:"address"`
	PhoneNo           sql.NullString `json:"phone_no"`
	AadhaarNo         sql.NullString `json:"aadhaar_no"`
	Status            sql.NullInt32  `json:"status"`
	IsActive          sql.NullInt32  `json:"is_active"`
	CreatedDate       sql.NullTime   `json:"created_date"`
	UpdatedDate       sql.NullTime   `json:"updated_date"`
	DeletedDate       sql.NullTime   `json:"deleted_date"`
}

type TypeAvailability struct {
	ID                int32         `json:"id"`
	AvailabilityID    sql.NullInt32 `json:"availability_id"`
	ServiceProviderID sql.NullInt32 `json:"service_provider_id"`
	Status            sql.NullInt32 `json:"status"`
	IsActive          sql.NullInt32 `json:"is_active"`
	CreatedDate       sql.NullTime  `json:"created_date"`
	UpdatedDate       sql.NullTime  `json:"updated_date"`
	DeletedDate       sql.NullTime  `json:"deleted_date"`
}

type User struct {
	ID                int32          `json:"id"`
	Username          sql.NullString `json:"username"`
	FirstName         sql.NullString `json:"first_name"`
	LastName          sql.NullString `json:"last_name"`
	PrePassword       sql.NullString `json:"pre_password"`
	Password          sql.NullString `json:"password"`
	EncryptedPasswrod sql.NullString `json:"encrypted_passwrod"`
	Address           sql.NullString `json:"address"`
	PhoneNo           sql.NullString `json:"phone_no"`
	AadhaarNo         sql.NullString `json:"aadhaar_no"`
	Lat         	  sql.NullFloat64 `json:"lat"`
	Lon         	  sql.NullFloat64 `json:"lon"`
	Status            sql.NullInt32  `json:"status"`
	IsActive          sql.NullInt32  `json:"is_active"`
	CreatedDate       sql.NullTime   `json:"created_date"`
	UpdatedDate       sql.NullTime   `json:"updated_date"`
	DeletedDate       sql.NullTime   `json:"deleted_date"`
}
